from ui.managers.abstract import AbstractWindow
from ui.managers.abstract import AbstractGUIManager
from ui.managers.calibration import CalibrationManager
from ui.managers.dots_creator import DotsCreatorManager
from ui.managers.images import ImagesManager
from ui.managers.processing import ProcessingManager
from ui.managers.project import ProjectManager
from ui.managers.settings import SettingsManager
from ui.managers.styles import StylesManager
